base_404 = ('https://www.python.org/11111/',
            'https://www.python.org/~peterson/pubkey.asc',
            'https://www.python.org/~larry/larrygpg.asc',
            'https://www.python.org/~anthony/anthonypub.asc',
            'https://www.python.org/~gbrandl/gbrandlpub.asc',
            'https://www.python.org/~nad/nadpub.asc',
            'https://www.python.org/~nad/nadAA65421D.asc',
            'http://www.python.org/topics/tkinter/',
            'https://www.python.org/about/success/projectpipe/projectPipeArchitecture.png',
            'http://www.python.org/doc/current/lib/module-BaseHTTPServer.html',
            'http://www.python.org/pycon/2005/papers/14/Paper14/HTML/paper/Paper14.mht',
            'https://www.python.org/download/releases/2.5.1/python-2.5.1.ia64.msi.asc',
            'https://www.python.org/download/releases/2.5.1/Python-2.5.1.tar.bz2.asc',
            'https://www.python.org/download/releases/2.5.1/Python25.chm.asc',
            'https://www.python.org/download/releases/2.5.1/python-2.5.1.amd64.msi.asc',
            'https://www.python.org/download/releases/2.5.1/python-2.5.1.msi.asc',
            'https://www.python.org/download/releases/2.5.1/python-2.5.1-macosx.dmg.asc',
            'https://www.python.org/download/releases/2.5.1/Python-2.5.1.tgz.asc',
            'https://www.python.org/download/releases/2.5.1/NEWS.txt',
            'https://www.python.org/download/releases/2.5.1/md5sum.py',
            'https://www.python.org/doc/2.5/whatsnew/whatsnew25.html',
            'http://www.python.org/doc/2.5/whatsnew/whatsnew25.html',
            'https://www.python.org/download/releases/2.2.2/md5sum.py',
            'https://www.python.org/doc/2.2.2',
            'https://www.python.org/download/releases/2.2.2/NEWS.txt',
            'https://www.python.org/doc/2.2.2/whatsnew/',
            'https://www.python.org/download/releases/2.5.2/python-2.5.2.amd64.msi.asc',
            'https://www.python.org/download/releases/2.5.2/python-2.5.2.msi.asc',
            'https://www.python.org/download/releases/2.5.2/Python-2.5.2.tgz.asc',
            'https://www.python.org/download/releases/2.5.2/Python25.chm.asc',
            'https://www.python.org/download/releases/2.5.2/python-2.5.2.ia64.msi.asc',
            'https://www.python.org/download/releases/2.5.2/md5sum.py',
            'https://www.python.org/download/releases/2.5.2/NEWS.txt',
            'https://www.python.org/download/releases/2.5.2/Python-2.5.2.tar.bz2.asc',
            'https://www.python.org/download/releases/2.5.2/python-2.5.2-macosx.dmg.asc',
            'https://www.python.org/download/releases/2.2.1/md5sum.py', 'https://www.python.org/doc/2.2.1/whatsnew/',
            'https://www.python.org/download/releases/2.2.1/NEWS', 'https://www.python.org/doc/2.2.1/',
            'https://www.python.org/download/releases/2.3.1/md5sum.py',
            'https://www.python.org/download/releases/2.3/mro/mro.txt', 'https://www.python.org/doc/2.3.1/',
            'https://www.python.org/doc/2.3/whatsnew/', 'https://www.python.org/download/releases/2.3.1/ChangeLog.txt',
            'https://www.python.org/download/releases/2.3.1/NEWS.txt',
            'https://www.python.org/download/releases/2.3.1/Python-2.3.1.tgz.asc',
            'https://www.python.org/download/releases/2.3.1/Python-2.3.1.exe.asc',
            'https://www.python.org/download/releases/2.6.3/Python-2.6.3.tgz.asc',
            'https://www.python.org/download/releases/2.6.3/NEWS.txt',
            'https://www.python.org/download/releases/2.6.3/Python-2.6.3.tar.bz2.asc',
            'https://www.python.org/download/releases/2.6.3/license',
            'https://www.python.org/download/releases/2.6.3/python-2.6.3.amd64.msi.asc',
            'http://www.python.org/doc/2.6.3/download',
            'https://www.python.org/download/releases/2.6.3/python-2.6.3.msi.asc',
            'https://www.python.org/download/releases/2.6.3/python-2.6.3-macosx.dmg.asc',
            'http://www.python.org/doc/2.6.3', 'https://www.python.org/doc/2.3.4/whatsnew/',
            'https://www.python.org/download/releases/2.3.4/NEWS.txt',
            'https://www.python.org/download/releases/2.3.4/Python-2.3.4.tgz.asc', 'https://www.python.org/doc/2.3.4/',
            'https://www.python.org/download/releases/2.3.4/md5sum.py',
            'https://www.python.org/download/releases/2.3.4/Python-2.3.4.exe.asc',
            'https://www.python.org/download/releases/2.3.4/Python-2.3.4.tar.bz2.asc',
            'https://www.python.org/download/releases/2.2.3/NEWS.txt',
            'https://www.python.org/download/releases/2.2.3/md5sum.py', 'https://www.python.org/doc/2.2.3/whatsnew/',
            'https://www.python.org/doc/2.2.3', 'https://www.python.org/download/releases/2.5/md5sum.py',
            'https://www.python.org/download/releases/2.5/IDLENEWS.txt',
            'https://www.python.org/download/releases/2.5/NEWS.txt', 'http://www.python.org/doc/2.6/download',
            'https://www.python.org/download/releases/2.6.1/python-2.6.1.msi.asc',
            'https://www.python.org/download/releases/2.6.1/python-2.6.1.amd64.msi.asc',
            'https://www.python.org/download/releases/2.6.1/NEWS.txt',
            'https://www.python.org/download/releases/2.6.1/Python-2.6.1.tar.bz2.asc',
            'https://www.python.org/download/releases/2.6.1/python-2.6.1-macosx2008-12-06.dmg.asc',
            'https://www.python.org/download/releases/2.6.1/Python-2.6.1.tgz.asc', 'http://www.python.org/doc/2.6',
            'https://www.python.org/download/releases/2.5.3/python-2.5.3.amd64.msi.asc',
            'https://www.python.org/download/releases/2.5.3/python-2.5.3.msi.asc',
            'https://www.python.org/download/releases/2.5.3/python-2.5.3-macosx.dmg.asc',
            'https://www.python.org/download/releases/2.5.3/python-2.5.3.ia64.msi.asc',
            'https://www.python.org/download/releases/2.5.3/NEWS.txt',
            'https://www.python.org/download/releases/2.5.3/Python-2.5.3.tgz.asc',
            'https://www.python.org/download/releases/2.5.3/md5sum.py',
            'https://www.python.org/download/releases/2.5.3/Python-2.5.3.tar.bz2.asc',
            'https://www.python.org/download/releases/2.5.3/Python25.chm.asc',
            'https://www.python.org/download/releases/2.6.2/NEWS.txt', 'http://www.python.org/doc/2.6.2',
            'https://www.python.org/download/releases/2.6.2/python-2.6.2.msi.asc',
            'https://www.python.org/download/releases/2.6.2/Python-2.6.2.tgz.asc',
            'https://www.python.org/download/releases/2.6.2/python262.chm.asc',
            'https://www.python.org/download/releases/2.6.2/python-2.6.2-macosx2009-04-16.dmg.sig',
            'http://www.python.org/doc/2.6.2/download',
            'https://www.python.org/download/releases/2.6.2/python-2.6.2.amd64.msi.asc',
            'https://www.python.org/download/releases/2.6.2/Python-2.6.2.tar.bz2.asc',
            'https://www.python.org/download/releases/2.7.2/Python-2.7.2.tgz.asc',
            'https://www.python.org/download/releases/2.7.2/python-2.7.2.msi.asc',
            'https://www.python.org/download/releases/2.7.2/python-2.7.2-macosx10.3.dmg.asc',
            'https://www.python.org/download/releases/2.7.2/python-2.7.2.amd64-pdb.zip.asc',
            'https://www.python.org/download/releases/2.7.2/python-2.7.2-pdb.zip.asc',
            'https://www.python.org/download/releases/2.7.2/Python-2.7.2.tar.xz.asc',
            'https://www.python.org/download/releases/2.7.2/python-2.7.2.amd64.msi.asc',
            'https://www.python.org/download/releases/2.7.2/Python-2.7.2.tar.bz2.asc',
            'https://www.python.org/download/releases/2.7.2/python-2.7.2-macosx10.6.dmg.asc',
            'https://www.python.org/2.4/msi.html', 'https://www.python.org/doc/2.4.1/',
            'https://www.python.org/download/releases/2.4.1/Python-2.4.1.tgz.asc',
            'https://www.python.org/download/releases/2.4.1/NEWS.html',
            'https://www.python.org/doc/2.4/whatsnew/whatsnew24.html',
            'https://www.python.org/download/releases/2.4.1/md5sum.py',
            'https://www.python.org/download/releases/2.4.1/MacPython-OSX-2.4.1-1.dmg.asc',
            'https://www.python.org/2.4/highlights.html', 'https://www.python.org/2.3/',
            'https://www.python.org/download/releases/2.4.1/python-2.4.1.msi.asc',
            'https://www.python.org/download/releases/2.4.1/python-2.4.1.ia64.msi.asc',
            'https://www.python.org/download/releases/2.4.1/Python-2.4.1.tar.bz2.asc',
            'https://www.python.org/2.4/index.html',
            'https://www.python.org/download/releases/2.6.5/Python-2.6.5.tgz.asc',
            'https://www.python.org/download/releases/2.6.5/Python-2.6.5.tar.bz2.asc',
            'https://www.python.org/download/releases/2.6.5/python-2.6.5.amd64.msi.asc',
            'https://www.python.org/download/releases/2.6.5/NEWS.txt',
            'https://www.python.org/download/releases/2.6.5/python-2.6.5.sig',
            'https://www.python.org/download/releases/2.6.5/python-2.6.5.msi.asc',
            'https://www.python.org/download/releases/2.3.2/md5sum.py',
            'https://www.python.org/download/releases/2.3.2/Python-2.3.2.tgz.asc',
            'https://www.python.org/download/releases/2.3.2/Python-2.3.2.tar.bz2.asc',
            'https://www.python.org/download.releases/2.3/mro',
            'https://www.python.org/download/releases/2.3.2/NEWS.txt',
            'https://www.python.org/download/releases/2.3.2/Python-2.3.2-1.exe.asc',
            'https://www.python.org/doc/2.3.2/',
            'https://www.python.org/download/releases/2.6.6/Python-2.6.6.tar.bz2.asc',
            'https://www.python.org/download/releases/2.6.6/python-2.6.6.msi.asc',
            'https://www.python.org/download/releases/2.6.6/python-2.6.6-macosx10.3.dmg.asc',
            'https://www.python.org/download/releases/2.6.6/Python-2.6.6.tgz.asc',
            'https://www.python.org/download/releases/2.6.6/NEWS.txt',
            'https://www.python.org/download/releases/2.6.6/python266.chm.asc',
            'https://www.python.org/download/releases/2.6.6/python-2.6.6.amd64.msi.asc',
            'https://www.python.org/download/releases/2.6.4/python-2.6.4_macosx10.3.dmg.asc',
            'http://www.python.org/doc/2.6.4', 'https://www.python.org/download/releases/2.6.4/Python-2.6.4.tgz.asc',
            'https://www.python.org/download/releases/2.6.4/license',
            'https://www.python.org/download/releases/2.6.4/Python-2.6.4.tar.bz2.asc',
            'https://www.python.org/download/releases/2.6.4/NEWS.txt',
            'https://www.python.org/download/releases/2.6.4/python-2.6.4.msi.asc',
            'https://www.python.org/download/releases/2.6.4/python-2.6.4.amd64.msi.asc',
            'http://www.python.org/doc/2.6.4/download',
            'https://www.python.org/download/releases/2.6/python-2.6-macosx2008-10-01.dmg.asc',
            'https://www.python.org/download/releases/2.6/NEWS.txt',
            'https://www.python.org/download/releases/2.6/Python-2.6.tgz.asc',
            'https://www.python.org/download/releases/2.6/python-2.6.amd64.msi.asc',
            'https://www.python.org/download/releases/2.6/Python-2.6.tar.bz2.asc',
            'https://www.python.org/download/releases/2.6/python-2.6.msi.asc',
            'https://www.python.org/download/releases/2.1.2/md5sum.py',
            'https://www.python.org/download/releases/2.1.3/NEWS.txt', 'https://www.python.org/doc/2.1.3/',
            'https://www.python.org/download/releases/2.5.4/python-2.5.4-macosx.dmg.asc',
            'https://www.python.org/download/releases/2.5.4/Python25.chm.asc',
            'https://www.python.org/download/releases/2.5.4/md5sum.py',
            'https://www.python.org/download/releases/2.5.4/Python-2.5.4.tar.bz2.asc',
            'https://www.python.org/download/releases/2.5.4/NEWS.txt',
            'https://www.python.org/download/releases/2.5.4/python-2.5.4.msi.asc',
            'https://www.python.org/download/releases/2.5.4/Python-2.5.4.tgz.asc',
            'https://www.python.org/download/releases/2.5.4/python-2.5.4.ia64.msi.asc',
            'https://www.python.org/download/releases/2.5.4/python-2.5.4.amd64.msi.asc',
            'https://www.python.org/download/releases/2.3.3/Python-2.3.3.tgz.asc',
            'https://www.python.org/2.2.3/descrintro', 'https://www.python.org/doc/2.3.3/whatsnew/',
            'https://www.python.org/download/releases/2.3.3/Python-2.3.3.tar.bz2.asc',
            'https://www.python.org/doc/2.3.3/', 'https://www.python.org/download/releases/2.3.3/md5sum.py',
            'https://www.python.org/download/releases/2.3.3/Python-2.3.3.exe.asc',
            'https://www.python.org/download/releases/2.3.3/NEWS.txt',
            'https://www.python.org/download/releases/3.0.1/NEWS.txt', 'https://www.python.org/doc/2.3.5/',
            'https://www.python.org/download/releases/2.3.5/Python-2.3.5.tgz.asc',
            'https://www.python.org/download/releases/2.3.5/Python-2.3.5.exe.asc',
            'https://www.python.org/download/releases/2.3.5/Python-2.3.5.tar.bz2.asc',
            'https://www.python.org/download/releases/2.3.5/md5sum.py',
            'https://www.python.org/download/releases/2.0.1/NEWS.txt', 'https://www.python.org/doc/2.0.1/',
            'https://www.python.org/download/releases/2.0.1/md5sum.py', 'https://www.python.org/doc/2.3/',
            'https://www.python.org/download/releases/2.3/md5sum.py',
            'https://www.python.org/download/releases/2.3/Python-2.3.tgz.asc',
            'https://www.python.org/download/releases/2.3/NEWS.txt',
            'https://www.python.org/download/releases/2.3/Python-2.3.exe.asc',
            'https://www.python.org/download/releases/2.7.1/python-2.7.1.msi.asc',
            'https://www.python.org/download/releases/2.7.1/python-2.7.1.amd64.msi.asc',
            'https://www.python.org/download/releases/2.7.1/Python-2.7.1.tar.bz2.asc',
            'https://www.python.org/download/releases/2.7.1/python-2.7.1-macosx10.6.dmg.asc',
            'https://www.python.org/download/releases/2.7.1/python-2.7.1-macosx10.3.dmg.asc',
            'https://www.python.org/download/releases/2.7.1/Python-2.7.1.tgz.asc',
            'https://www.python.org/download/releases/2.7.1/python-2.7.1.amd64-pdb.zip.asc',
            'https://www.python.org/download/releases/2.7.1/python-2.7.1-pdb.zip.asc',
            'https://www.python.org/dev/peps/pep-0237.html', 'https://www.python.org/dev/peps/pep-0253.html',
            'https://www.python.org/dev/peps/pep-0238.html', 'https://www.python.org/download/releases/2.2/md5sum.py',
            'https://www.python.org/doc/2.2/', 'https://www.python.org/doc/2.2.3/whatsnew/whatsnew22.html',
            'https://www.python.org/dev/peps/pep-0255.html', 'https://www.python.org/download/releases/2.2/NEWS.txt',
            'https://www.python.org/dev/peps/pep-0234.html', 'https://www.python.org/dev/peps/pep-0252.html',
            'http://www.python.org/dev/intro/', 'https://www.python.org/doc/essays/sigs/edu-sig/',
            'http://www.python.org/workshops/1997-10/proceedings/',
            'https://www.python.org/doc/essays/metaclasses/Trace.py',
            'https://www.python.org/doc/essays/metaclasses/Simple.py', 'http://www.python.org/cgi-bin/faqw.py',
            'https://www.python.org/doc/essays/metaclasses/meta-vladimir.txt',
            'https://www.python.org/doc/essays/metaclasses/Meta.py',
            'https://www.python.org/doc/essays/metaclasses/Eiffel.py',
            'https://www.python.org/doc/essays/metaclasses/Enum.py',
            'http://www.python.org/cgi-bin/faqw.py?req=show&file=faq06.022.htp',
            'https://www.python.org/doc/essays/metaclasses/Synch.py',
            'http://www.python.org/doc/lib/module-exceptions.html', 'https://www.python.org/doc/api/refcounts.html',
            'https://www.python.org/download/releases/2.2/descrintro/bugs', 'http://www.python.org/tim_one/',
            'https://www.python.org/download/releases/2.3.7/Python-2.3.7.tgz.asc',
            'https://www.python.org/download/releases/2.3.7/Python-2.3.7.tar.bz2.asc',
            'http://www.python.org/doc/2.3.5/whatsnew/whatsnew23.html',
            'https://www.python.org/download/releases/2.3.7/md5sum.py',
            'https://www.python.org/download/releases/2.3.7/NEWS.txt',
            'https://www.python.org/download/releases/2.6.7/NEWS.txt',
            'https://www.python.org/download/releases/2.3.6/md5sum.py',
            'https://www.python.org/download/releases/2.3.6/Python-2.3.6.tar.bz2.asc',
            'https://www.python.org/download/releases/2.3.6/NEWS.txt',
            'https://www.python.org/download/releases/2.3.6/Python-2.3.6.tgz.asc',
            'https://www.python.org/download/releases/2.4.5/md5sum.py',
            'https://www.python.org/download/releases/2.4.5/Python-2.4.5.tar.bz2.asc',
            'http://www.python.org/doc/2.4.4/whatsnew/whatsnew24.html',
            'https://www.python.org/download/releases/2.4.5/Python-2.4.5.tgz.asc',
            'https://www.python.org/download/releases/2.4.5/NEWS.txt',
            'http://www.python.org/doc/2.4.3/whatsnew/whatsnew24.html',
            'https://www.python.org/download/releases/2.6.8/NEWS.txt',
            'https://www.python.org/download/releases/2.5.5/Python-2.5.5.tar.bz2.asc',
            'https://www.python.org/download/releases/2.5.5/Python-2.5.5.tgz.asc',
            'https://www.python.org/download/releases/2.5.5/NEWS.txt',
            'https://www.python.org/download/releases/2.5.6/NEWS.txt',
            'https://www.python.org/download/releases/2.5.6/download/releases/2.5.4/',
            'https://www.python.org/download/releases/2.4.6/Python-2.4.6.tar.bz2.asc',
            'https://www.python.org/download/releases/2.4.6/md5sum.py',
            'https://www.python.org/download/releases/2.4.6/Python-2.4.6.tgz.asc',
            'https://www.python.org/download/releases/2.4.6/NEWS.txt',
            'https://www.python.org/downloads/release/3.1.4/',
            'https://www.python.org/files/success/rackspace/datacenter.jpg',
            'https://www.python.org/files/success/carmanah/xwalk-proto-zoom.jpg',
            'http://www.python.org/doc/2.2.1/whatsnew/whatsnew22.html',
            'http://www.python.org/search/hypermail/python-1994q1/0301.html',
            'http://www.python.org/doc/current/library/imp.html', 'http://www.python.org/doc/essays/stdexceptions.html',
            'https://www.python.org/psf/contrib/doc-contrib-form/',
            'http://www.python.org/doc/essays/ppt/python10/py10keynote.pdf',
            'http://www.python.org/moin/PythonDecorators', 'http://www.python.org/doc/essays/ppt/euro2004/euro2004.pdf',
            'http://www.python.org/workshops/2002-02/', 'http://www.python.org/dev/peps/pep-xxxx/',
            'https://www.python.org/dev/peps/pep-0451/The%22target%22parameteroffind_spec()',
            'http://www.python.org/doc/essays/ppt/pycon2003/pycon2003.ppt',
            'http://www.python.org/doc/essays/ppt/regrets/PythonRegrets.pdf', 'http://www.python.org/moin/Python3.0',
            'http://www.python.org/doc/essays/styleguide.html',
            'http://www.python.org/doc/current/lib/module-email.html',
            'http://www.python.org/~bwarsaw/software/pyware.html',
            'http://www.python.org/workshops/1997-10/proceedings/loewis.html',
            'http://www.python.org/psf/contrib-draft.html',
            'http://www.python.org/moin/PythonSoftwareFoundationLicenseV2Easy',
            'http://www.python.org/moin/WebsiteRedesignProposal', 'https://www.python.org/jobs/3189/',
            'https://www.python.org/jobs/3192/', 'https://www.python.org/jobs/3196/',
            'https://www.python.org/success-stories/projectpipe/projectPipeArchitecture.png',
            'https://www.python.org/success-stories/gravityzoo/GravityZoo', 'http://www.python.org/doc/2.5/whatsnew/',
            'https://www.python.org/doc/2.4/', 'https://www.python.org/download/releases/2.4/Python-2.4.tgz.asc',
            'https://www.python.org/download/releases/2.4/python-2.4.ia64.msi.asc',
            'https://www.python.org/download/releases/2.4/python-2.4.msi.asc',
            'https://www.python.org/download/releases/2.4/md5sum.py',
            'https://www.python.org/download/releases/2.4/Python-2.4.tar.bz2.asc', 'http://www.python.org/2.4.4/',
            'http://www.python.org/2.3.6/', 'https://www.python.org/download/releases/2.1/NEWS.txt',
            'https://www.python.org/doc/2.1/', 'https://www.python.org/doc/2.1/download.html',
            'https://www.python.org/download/releases/2.1/md5sum.py',
            'https://www.python.org/download/releases/2.2.3/descrintro.html',
            'https://www.python.org/download/releases/2.3/mro.html',
            'https://www.python.org/download/releases/2.2/descrintro.html',
            'https://www.python.org/download/releases/2.4.4/NEWS.txt',
            'https://www.python.org/download/releases/2.4.4/python-2.4.4-macosx2006-10-18.dmg.asc',
            'https://www.python.org/download/releases/2.4.4/md5sum.py',
            'https://www.python.org/download/releases/2.4.4/python24.chm.asc',
            'https://www.python.org/download/releases/2.4.4/Python-2.4.4.tar.bz2.asc',
            'https://www.python.org/download/releases/2.4.4/python-2.4.4.msi.asc',
            'https://www.python.org/download/releases/2.4.4/python-2.4.4.ia64.msi.asc',
            'https://www.python.org/download/releases/2.4.4/Python-2.4.4.tgz.asc',
            'https://www.python.org/download/releases/2.2.1/descrintro/bugs', 'http://www.python.org/2.3.1/',
            'https://www.python.org/download/releases/2.3/highlights/NEWS.txt',
            'http://www.python.org/2.2.2/descrintro.html',
            'http://www.python.org/moin/Python_202_2e3_2e1_20Platform_20Reports',
            'http://www.python.org/doc/current/lib/', 'http://www.python.org/2.2/',
            'http://www.python.org/2.2/descrintro.html', 'http://www.python.org/2.3.2/', 'http://www.python.org/2.3.3/',
            'https://www.python.org/download/releases/2.0/new-python.htm', 'https://www.python.org/doc/2.0/',
            'http://www.python.org/2.3/',
            'https://www.python.org/download/releases/2.4.3/Universal-MacPython-2.4.3-2006-04-07.dmg.asc',
            'https://www.python.org/download/releases/2.4.3/md5sum.py',
            'https://www.python.org/download/releases/2.4.3/NEWS.txt',
            'https://www.python.org/download/releases/2.4.3/Python-2.4.3.tar.bz2.asc',
            'https://www.python.org/download/releases/2.4.3/python-2.4.3.ia64.msi.asc',
            'http://www.python.org/doc/2.4/whatsnew/whatsnew24.html', 'https://www.python.org/doc/2.4.3/',
            'https://www.python.org/download/releases/2.4.3/Python-2.4.3.tgz.asc',
            'https://www.python.org/download/releases/2.4.3/python-2.4.3.msi.asc',
            'https://www.python.org/download/releases/2.4.2/md5sum.py',
            'https://www.python.org/download/releases/2.4.2/Python-2.4.2.tgz.asc', 'https://www.python.org/doc/2.4.2/',
            'https://www.python.org/download/releases/2.4.2/python-2.4.2.ia64.msi.asc',
            'https://www.python.org/download/releases/2.4.2/NEWS.txt',
            'https://www.python.org/download/releases/2.4.2/python-2.4.2.msi.asc',
            'https://www.python.org/download/releases/2.4.2/Python-2.4.2.tar.bz2.asc',
            'https://www.python.org/download/releases/2.4.2/MacPython-OSX-2.4.2-1.dmg.asc',
            'https://www.python.org/files/psf/records/exemption.png',
            'https://www.python.org/files/psf/records/exemption.tif', 'http://www.python.org/pycon/2005/',
            'http://www.python.org/moin/PyConDC2005/Sprints',
            'https://www.python.org/community/sigs/retired/pythonwin-sig/mission',
            'https://www.python.org/community/sigs/retired/progenv-sig/mission',
            'https://www.python.org/files/sigs/dev-day-notes.txt',
            'https://www.python.org/community/sigs/retired/pattern-sig/mission',
            'https://www.python.org/community/sigs/retired/locator-sig/mission',
            'https://www.python.org/community/sigs/current/catalog-sig/', 'https://www.python.org/community/index.html',
            'https://www.python.org/files/sigs/ipc8_talk.ag.gz', 'https://www.python.org/files/sigs/sc_submission.html',
            'https://www.python.org/files/sigs/ipc8_paper.html', 'https://www.python.org/files/sigs/ipc8_paper.ps.gz',
            'https://www.python.org/files/sigs/ipc8_talk.ppt.gz', 'https://www.python.org/files/sigs/ipc8_paper.pdf.gz',
            'http://www.python.org/psf/psf-contributor-agreement.html',
            'http://www.python.org/psf/codeofconduct/Reworked', 'http://www.python.org/2006/cfp',
            'https://www.python.org/psf/records/board/minutes/2008-12-08/www.obooe.org',
            'http://www.python.org/workshops/oscon2002')

print(len(base_404))  # 352

f = open("base_404.txt", "w+")

for link in base_404:
    # f.write(link + "\n")
    # f.write("%s\n" % link)
    f.write("{}{}".format(link, "\n"))
f.close()
